### PR TITLE
retrieve data from backend for product detail

### PR DESCRIPTION
**Pull request by Euna-kim-1**
**Jira Ticket**<br>
Link: https://derek-team-lva74agprdbm.atlassian.net/browse/SP-60, https://derek-team-lva74agprdbm.atlassian.net/browse/SP-64

**Description**<br>
_Add a sensible description to this pull request:_  Connect the backend code to fetch data for product description page

- Added:
- Changed: `product/[id]/page.tsx`, `components/products/productDetail.tsx`, `components/products/productDetail.tsx`, `entitles/Product.ts`
- Refactored:
- Removed:

**Screenshots**<br>
(_drag and drop images here_)

**Unit Test**<br>
_Describe any unit tests or their results (if applicable):_

### CODE REVIEW

**Comment by JIYEON-H** [comment]
Is this code written based on the local branch backend?
image

**Comment by Euna-kim-1** [comment]
Yes the code written based on the local branch backend.

**Review by Eunji-Elly-Lee — COMMENTED** [review]
Great!

**Review by Eunji-Elly-Lee — APPROVED** [review]
.

**Pull request merged**
